#!/bin/bash

#
# Generate c-files for btrfs subcommands defined below
#

# Notes on linux capabilities:
#
# btrfs-subvolume-show, btrfs-subvolume-list, btrfs-send:
#  - CAP_FOWNER is only needed for O_NOATIME flag in open() system calls
#  - why CAP_SYS_ADMIN? shouldn't CAP_DAC_READ_SEARCH be enough?
#
# btrfs-receive:
#  - dependent on send-stream (see cmds-receive.c: "send_ops"):
#    CAP_CHOWN, CAP_MKNOD, CAP_SETFCAP (for "lsetxattr")
#
# btrfs-filesystem-usage:
#  - CAP_SYS_ADMIN is for BTRFS_IOC_TREE_SEARCH and BTRFS_IOC_FS_INFO
#    in order to provide full level of detail, see btrfs-filesystem(8)


makefile_out="Makefile.install_setcap"

splitcmd_list=""
setcap_lines=""

function gen_splitcmd {
    local name="$1"
    local dest="${1}.c"
    local cfile="$2"
    local entry="$3"
    local caps="$4"
    echo "generating: ${dest} (cfile=${cfile}, entry=${entry})"
    echo -e "/*\n * ${name}\n *\n * GENERATED BY splitcmd-gen.sh\n */\n" > $dest
    sed -e "s|@BTRFS_SPLITCMD_CFILE_INCLUDE@|${cfile}|g" \
        -e "s|@BTRFS_SPLITCMD_ENTRY@|${entry}|g" \
        splitcmd.c.in >> $dest
}

gen_splitcmd "btrfs-subvolume-show" \
             "cmds-subvolume.c" "cmd_subvol_show" \
             "cap_sys_admin,cap_fowner,cap_dac_read_search"

gen_splitcmd "btrfs-subvolume-list" \
             "cmds-subvolume.c" "cmd_subvol_list" \
             "cap_sys_admin,cap_fowner,cap_dac_read_search"

gen_splitcmd "btrfs-subvolume-snapshot" \
             "cmds-subvolume.c" "cmd_subvol_snapshot" \
             "cap_sys_admin,cap_fowner,cap_dac_override,cap_dac_read_search"

gen_splitcmd "btrfs-subvolume-delete" \
             "cmds-subvolume.c" "cmd_subvol_delete" \
             "cap_sys_admin,cap_dac_override"

gen_splitcmd "btrfs-send" \
             "cmds-send.c" "cmd_send" \
             "cap_sys_admin,cap_fowner,cap_dac_read_search"

gen_splitcmd "btrfs-receive" \
             "cmds-receive.c" "cmd_receive" \
             "cap_sys_admin,cap_fowner,cap_chown,cap_mknod,cap_setfcap,cap_dac_override,cap_dac_read_search"

gen_splitcmd "btrfs-filesystem-usage" \
             "cmds-fi-usage.c" "cmd_filesystem_usage" \
             "cap_sys_admin"

gen_splitcmd "btrfs-qgroup-destroy" \
             "cmds-qgroup.c" "cmd_qgroup_destroy" \
             "cap_sys_admin,cap_dac_override"
